# Generated by Django 5.1.6 on 2025-02-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('producer', models.CharField(max_length=200)),
                ('duration', models.IntegerField(help_text='Продолжительность фильма в секундах')),
            ],
        ),
    ]
